import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/components/app.header";
import Table from "@/components/app.body";
import { Container } from "react-bootstrap";
import Footer from "@/components/app.footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
