import "bootstrap/dist/css/bootstrap.min.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div>SỬ DỤNG LAYOUT ĐỂ REUSE-CODE GIÚP MK TÁI SỬ DỤNG CODE </div>
      <body>{children}</body>
    </html>
  );
}
